# Smart Agricultural Production Optimization Engine

## Data Preprocessing

### Objective

Prepare the dataset for machine learning by:

- Loading the dataset
- Separating features and target
- Encoding crop labels
- Splitting into training and testing datasets
- Scaling numerical features

In [ ]:
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import StandardScaler

import joblib

In [1]:
df = pd.read_csv("../data/raw/Crop_recommendation.csv")

df.head()

NameError: name 'pd' is not defined

In [2]:
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import StandardScaler

import joblib

In [3]:
df = pd.read_csv("../data/raw/Crop_recommendation.csv")

df.head()

    N   P   K  temperature   humidity        ph    rainfall label
0  90  42  43    20.879744  82.002744  6.502985  202.935536  rice
1  85  58  41    21.770462  80.319644  7.038096  226.655537  rice
2  60  55  44    23.004459  82.320763  7.840207  263.964248  rice
3  74  35  40    26.491096  80.158363  6.980401  242.864034  rice
4  78  42  42    20.130175  81.604873  7.628473  262.717340  rice

In [4]:
# Separate Features and Target

X = df.drop("label", axis=1)
y = df["label"]

print("Feature Shape :", X.shape)
print("Target Shape  :", y.shape)

Feature Shape : (2200, 7)
Target Shape  : (2200,)

In [5]:
X.head()

    N   P   K  temperature   humidity        ph    rainfall
0  90  42  43    20.879744  82.002744  6.502985  202.935536
1  85  58  41    21.770462  80.319644  7.038096  226.655537
2  60  55  44    23.004459  82.320763  7.840207  263.964248
3  74  35  40    26.491096  80.158363  6.980401  242.864034
4  78  42  42    20.130175  81.604873  7.628473  262.717340

In [6]:
y.head()

0    rice
1    rice
2    rice
3    rice
4    rice
Name: label, dtype: str

In [7]:
# Initialize Label Encoder
label_encoder = LabelEncoder()

# Encode the target labels
y_encoded = label_encoder.fit_transform(y)

print("First 10 Encoded Labels:")
print(y_encoded[:10])

First 10 Encoded Labels:
[20 20 20 20 20 20 20 20 20 20]

In [8]:
mapping = pd.DataFrame({
    "Crop": label_encoder.classes_,
    "Encoded Value": range(len(label_encoder.classes_))
})

mapping

           Crop  Encoded Value
0         apple              0
1        banana              1
2     blackgram              2
3      chickpea              3
4       coconut              4
5        coffee              5
6        cotton              6
7        grapes              7
8          jute              8
9   kidneybeans              9
10       lentil             10
11        maize             11
12        mango             12
13    mothbeans             13
14     mungbean             14
15    muskmelon             15
16       orange             16
17       papaya             17
18   pigeonpeas             18
19  pomegranate             19
20         rice             20
21   watermelon             21

In [9]:
# Split the dataset

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y_encoded,
    test_size=0.2,
    random_state=42,
    stratify=y_encoded
)

print("Training Features :", X_train.shape)
print("Testing Features  :", X_test.shape)
print("Training Labels   :", y_train.shape)
print("Testing Labels    :", y_test.shape)

Training Features : (1760, 7)
Testing Features  : (440, 7)
Training Labels   : (1760,)
Testing Labels    : (440,)

In [10]:
# Initialize the scaler
scaler = StandardScaler()

# Fit on training data and transform
X_train_scaled = scaler.fit_transform(X_train)

# Transform testing data
X_test_scaled = scaler.transform(X_test)

print("Training data scaled successfully.")
print("Testing data scaled successfully.")

Training data scaled successfully.
Testing data scaled successfully.

In [11]:
# Save preprocessing objects

joblib.dump(scaler, "../models/scaler.pkl")
joblib.dump(label_encoder, "../models/label_encoder.pkl")

print("Scaler and Label Encoder saved successfully!")

Scaler and Label Encoder saved successfully!